name: cis17b_connect4_final

services:
  web:
    image: php:8.3.7-apache
    ports:
      - 80:80
    volumes:
      - ./Connect4ProjectWebGUI:/var/www/html

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass

  adminer:
    image: adminer
    ports:
      - 8080:8080
